/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('ant-design-vue/es')['Affix']
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AAnchorLink: typeof import('ant-design-vue/es')['AnchorLink']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Basic: typeof import('./src/components/customDemo/demo/basic.vue')['default']
    BasicButton: typeof import('./src/components/Button/src/BasicButton.vue')['default']
    Demo: typeof import('./src/components/customDemo/demo/index.vue')['default']
    DemoBox: typeof import('./src/components/DemoBox.vue')['default']
    DemoContainer: typeof import('./src/components/demoContainer.vue')['default']
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    IconPicker: typeof import('./src/components/Icon/src/IconPicker.vue')['default']
    PopConfirmButton: typeof import('./src/components/Button/src/PopConfirmButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/Icon/src/SvgIcon.vue')['default']
  }
}
